import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

import KakakoBtn from "../components/kakao-share";
import FBBtn from "../components/fb-share";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <KakakoBtn />
        <FBBtn />
        <Link href="/question">
          <a>정원성향 테스트 하러가기</a>
        </Link>
      </main>
    </div>
  );
};

export default Home;
